const books = [
  { id: 1, nombre: "Cien años de soledad", autor: "Gabriel García Márquez", paginas: 471 },
  { id: 2, nombre: "1984", autor: "George Orwell", paginas: 328 },
  { id: 3, nombre: "Rayuela", autor: "Julio Cortázar", paginas: 688 },
  { id: 4, nombre: "Crimen y castigo", autor: "Fiódor Dostoyevski", paginas: 671 },
  { id: 5, nombre: "Don Quijote de la Mancha", autor: "Miguel de Cervantes", paginas: 863 },
  { id: 6, nombre: "El principito", autor: "Antoine de Saint-Exupéry", paginas: 96 },
  { id: 7, nombre: "Fahrenheit 451", autor: "Ray Bradbury", paginas: 194 },
  { id: 8, nombre: "Orgullo y prejuicio", autor: "Jane Austen", paginas: 279 },
  { id: 9, nombre: "La sombra del viento", autor: "Carlos Ruiz Zafón", paginas: 565 },
  { id: 10, nombre: "El túnel", autor: "Ernesto Sabato", paginas: 160 },
  { id: 11, nombre: "Ensayo sobre la ceguera", autor: "José Saramago", paginas: 352 },
  { id: 12, nombre: "El amor en los tiempos del cólera", autor: "Gabriel García Márquez", paginas: 368 },
  { id: 13, nombre: "Los juegos del hambre", autor: "Suzanne Collins", paginas: 374 },
  { id: 14, nombre: "El código Da Vinci", autor: "Dan Brown", paginas: 592 },
  { id: 15, nombre: "It", autor: "Stephen King", paginas: 1138 },
  { id: 16, nombre: "Drácula", autor: "Bram Stoker", paginas: 418 },
  { id: 17, nombre: "Frankenstein", autor: "Mary Shelley", paginas: 280 },
  { id: 18, nombre: "Los miserables", autor: "Victor Hugo", paginas: 1232 },
  { id: 19, nombre: "Madame Bovary", autor: "Gustave Flaubert", paginas: 384 },
  { id: 20, nombre: "La metamorfosis", autor: "Franz Kafka", paginas: 74 },
  { id: 21, nombre: "Matar a un ruiseñor", autor: "Harper Lee", paginas: 336 },
  { id: 22, nombre: "El lobo estepario", autor: "Hermann Hesse", paginas: 256 },
  { id: 23, nombre: "Trilogía de Nueva York", autor: "Paul Auster", paginas: 384 },
  { id: 24, nombre: "Tokio Blues", autor: "Haruki Murakami", paginas: 384 },
  { id: 25, nombre: "La insoportable levedad del ser", autor: "Milan Kundera", paginas: 320 },
  { id: 26, nombre: "El guardián entre el centeno", autor: "J.D. Salinger", paginas: 277 },
  { id: 27, nombre: "Sobre héroes y tumbas", autor: "Ernesto Sabato", paginas: 512 },
  { id: 28, nombre: "Pedro Páramo", autor: "Juan Rulfo", paginas: 124 },
  { id: 29, nombre: "Los detectives salvajes", autor: "Roberto Bolaño", paginas: 609 },
  { id: 30, nombre: "2666", autor: "Roberto Bolaño", paginas: 1126 }
];

export default books